# Generated by Django 3.2.13 on 2022-06-20 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_num', models.IntegerField()),
                ('order_num', models.CharField(max_length=7, unique=True)),
                ('price_dol', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_rub', models.DecimalField(decimal_places=2, max_digits=10)),
                ('get_data', models.DateField()),
            ],
        ),
    ]
