# Generated by Django 3.2.13 on 2022-06-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_order_order_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id_num',
            field=models.IntegerField(unique=True),
        ),
    ]
